version: '3'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: tail -f /dev/null

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /usr/sbin/sshd -D

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /usr/sbin/sshd -D